services:
  mem0_store:
    image: qdrant/qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
    volumes:
      - mem0_storage:/mem0/storage
  openmemory-mcp:
    image: mem0/openmemory-mcp:latest
    restart: unless-stopped
    environment:
      - OPENAI_API_KEY=sk-proj...
      - USER=Teck
      - QDRANT_HOST=mem0_store
      - QDRANT_PORT=6333
    depends_on:
      - mem0_store
    ports:
      - "8765:8765"
  openmemory-ui:
    image: mem0/openmemory-ui:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: "http://192.168.1.5:8765"
      NEXT_PUBLIC_USER_ID: "Teck"
      PORT: "3000"
      HOSTNAME: "0.0.0.0"
volumes:
  mem0_storage:
